# name of workflow
name: CI
# we want this workflow to run every time we push to the main
on:
  push:
    branches:
        - main
# we want to triiger it manually in the UI.
  workflow_dispatch:
# we will make first job a unit test job
jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
     # First job action to checkout the code
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          #after the branch is cloned it makes next runs much quicker
          cache-dependency-path: bugtracker-backend/go.sum

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      # The name that will appear in the UI
      - name: Execute Backend Unit Tests 
      # Specify the working directory that we want unit test to run
        working-directory: ./bugtracker-backend
      # Specify the shell commands that we want to run, we want to run all go tests.
      # For first run will fail as after defined that it runs on ubuntu-latest,
      # So we will have to install go before using it.
      # What we done before either to install go before run UT or using docker image that will install go tool.
      # But in github we can use special actions that have beeen predefined and will install go quickly on our github.
        run:                                                                       
          go test -v ./... 2>&1 | go-junit-report > test-results.xml

      - name: Publish Backend Test Results
        # to use pre-built, community-made action called test-reporter created by the user dorny
        uses: dorny/test-reporter@v1
        # to make sure that the test runs even it fails
        if: always()
        with:
          name: Backend Unit Tests Report
          path: bugtracker-backend/test-results.xml
          # Tells this action to expect a JUnit XML format, which is the specific structure jest-junit uses to log test results.
          reporter: jest-junit

  unit-tests-frontend:
    # it means i want to make backend to run first as they are runing sequential
    needs: unit-tests-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Node.jobs
        # its a github action used to setup the node for us its made by someone else
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
           #after the branch is cloned it makes next runs much quicker
          cache-dependency-path: bugtracker-frontend/package-lock.json



      - name: Execute Frontend Unit Tests
        working-directory: ./bugtracker-frontend
        run:
          npm ci
          npm test

      - name: Publish Frontend Test Results
        # to use pre-built, community-made action called test-reporter created by the user dorny
        uses: dorny/test-reporter@v1
        # to make sure that the test runs even it fails
        if: always()
        with:
          name: Frontend Unit Tests Report
          path: bugtracker-frontend/test-results.xml
          # Tells this action to expect a JUnit XML format, which is the specific structure jest-junit uses to log test results.
          reporter: jest-junit

